### ISSUE TITLE
Leaflet tilesrv

### ISSUE THREAD

**Issue by PrasanthPeddisetty** [jcupitt/tilesrv#2]
Hey! I'm trying to overlay a custom image's tiles on the fly on leaflet using tilesrv. Can I use tilesrv to do this because leaflet has a URI template for tileLayer as "http://{s}.somedomain.com/blabla/{z}/{x}/{y}{r}.png". Can tilesrv serve tiles in this format?
Also, I'm trying overlay images of sizes greater 300mb. Please do let me know how I can do this.

**Comment by jcupitt** [comment]
Sorry, I don't really have time to support this program, you're on your own.

You can set leaflet's URI template, you can also rewrite in the webserver, and of course you could modify the tilesrv sources to respond to any URI pattern.

I would consider using deepzoom instead of tilesrv, it's a lot simpler.
